### PR TITLE
English Dialogue improvements

### PR DESCRIPTION
**Pull request by craigmaloney**
Updating this based on Alex's already great translation. Added a few different words and phrasings to make it more natural.

### CODE REVIEW

**Comment by valvin1** [comment]
@Deevad i've just merged @craigmaloney pull request and ask review using github menu to @agryson (not sure it is to good way ;))

**Comment by agryson** [comment]
Looks great, nice catch on spiruline/spirulina!

**Comment by craigmaloney** [comment]
(Thank you. :) )

**Comment by Deevad** [comment]
Thank you for the review, and good job! I tweaked a bit the layout, pushed and I did an update for the XYZ page:
https://www.peppercarrot.com/XYZ/index.php?subfolder=ep22-WIP_en
Is it _"Ready-to-send-to-translation-mailing-list"_ ?  :-D

**Comment by agryson** [comment]
We are go for launch!

**Pull request merged**
