### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by Willem3141**
Hi @M1dgard, I did a first pass over the text. Feel free to comment on anything 😄 

Do you have suggestions for the episode title? I hate ‘Het stemsysteem’ as it sounds very strange in my ears, but I couldn't find anything better (maybe just ‘Televoting’, but that may give away too much ...)

To do:

* [x] Decide on title
* [x] Proofreading
* [x] Insert boilerplate text on the last page

### CODE REVIEW

**Comment by ghost** [comment]
Hi @Willem3141, thanks!

"Het stemsysteem" is weird indeed. I thought "De stembakjes", I don't know if that would be an acceptable word up in NL. I don't think that gives away *too* much; they are introduced fairly early (page 2). Or " kiessysteem", or does that make it sound like it's about political elections?

**Comment by ghost** [comment]
"De beurt is aan Shichimi!" sounds uncomfortable. I'd rather say "Dan is het nu aan Shichimi!"

"briljante", I'd say "schitterende", preserves the pun a bit better IMO.

"Vergeet wat ik net zei over dit systeem …" could be made a bit stronger, e.g. "Vergeet alles wat ik over dit systeem gezegd heb …" Standalone both phrases sound equally good, but in the flow of the story, I think the latter is better.

**Comment by ghost** [comment]
I've put "De ~~stembakjes~~ **stemkastjes**" as title for now.

**Comment by Willem3141** [comment]
Sorry for me being slow, and thanks for the fixes!

I like the new title much more than "het stemsysteem" or "het kiessysteem", but _stembakjes_ sounds slightly weird in NL; it would be _stemkastjes_ here. Is that acceptable in BE?

_ah, I see I put another "nou" in there... sorry, habits die hard_ 😉

**Comment by ghost** [comment]
> but stembakjes sounds slightly weird in NL; it would be stemkastjes here. Is that acceptable in BE?

Yes, it sounds a bit more NL-ish but it is acceptable. It's also what I already put in there, my previous comment was wrong XD

Shall I also apply the changes in [the comment before](https://github.com/Deevad/peppercarrot_ep22_translation/pull/7#issuecomment-305649505) then?

**Comment by Willem3141** [comment]
I processed all of your comments; I think we are ready to merge ...

**Pull request merged**
